[package]
name = "cepack_test"
version = "0.0.2"
authors = ["泡泡纸 <paopaozhi@hotmail.com>"]

[depend]
gitmoji = {url = "https://github.com/carloscuesta/gitmoji", version = "v3.14.0"}
ulog = { url = "https://github.com/rdpoor/ulog", version = "0.0.1" }

[dependencies]
gitmoji = {url = "https://github.com/carloscuesta/gitmoji", version = "v3.14.0"}
ulog = { url = "https://github.com/rdpoor/ulog", version = "0.0.1" }