[project]
name = "cepack"
version = "0.0.3"
authors = [{ name = "paopaozhi", email = "paopaozhi@hotmail.com" }]
dependencies = ["typer","toml","requests"]
description = "embedded pack manage"
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-3.0"
classifiers = [
  "Programming Language :: Python :: 3.9",
  "License :: OSI Approved :: GPL-3.0 License",
  "Operating System :: OS Independent",
]

[project.scripts]
cepack = "cepack.main:run"

[build-system]
# requires = ["setuptools>=61.0"]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/paopaozhi/cepack"
"Bug Tracker" = "https://github.com/paopaozhi/cepack/issues"

[tool.setuptools]
# ...
package-dir = {"" = "."}
